/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AbiErc20 {
  abi:
    | []
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          anonymous: boolean;
          inputs:
            | []
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          type: string;
          [k: string]: unknown;
        }
      ]
    | [
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs: unknown[];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          constant: boolean;
          inputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          outputs:
            | []
            | [
                {
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          payable: boolean;
          stateMutability: string;
          type: string;
          [k: string]: unknown;
        },
        {
          anonymous: boolean;
          inputs:
            | []
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          type: string;
          [k: string]: unknown;
        },
        {
          anonymous: boolean;
          inputs:
            | []
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ]
            | [
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                },
                {
                  indexed: boolean;
                  name: string;
                  type: string;
                  [k: string]: unknown;
                }
              ];
          name: string;
          type: string;
          [k: string]: unknown;
        }
      ];
  [k: string]: unknown;
}
